name: "Multi Docker workflow"

on: 
  push: 
    branches:
      - master


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out repo"
        uses: actions/checkout@v2

      - name: Build docker image
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}//react-client -f ./client/Dockerfile.dev ./client
      - name: Test app
        run: docker run ${{ secrets.DOCKER_HUB_USERNAME }}//react-client yarn test

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/react-client:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
